name: Calypso
version: '0.2.0'
main: me.mrbedrockpy.calypso.Calypso
api-version: 1.19

commands:
  infoplayers:
    description: Выводит информацию о всех игроках на сервере
  apocalypseevent:
    description: включает/выключает режим ивента
  adminwhitelist:
    description: включает/выключает режим тех работ
  bossevent:
    description: включает/выключает режим тех работ